name: build-windows
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: release
          submodules: recursive

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '5.15.2'
          arch: win64_msvc2019_64

      - name: Configure and Build
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          cmake --build . --config Release

      - name: Upload binary to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/Release/kdictionary-lingoes.exe
          name: 'Latest Build'
          body: 'Automatically built on windows-latest, from master commit ${{ github.sha }}'
          tag_name: latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
